### ISSUE TITLE
constructor should not do conversions

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/variant#100]
The templated constructor `template <class T> variant(const T& t)` should be enabled only when `T` is explicitly one of the types of the variant. This will avoid unexpected conversions:

```
variant<bool, uint64_t> v(1234);
v.is<uint64_t>(); // false!
```

This is also consistent with [the current C++ variant proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0088r0.pdf), which states for the constructor:

> The function shall not participate in overload resolution unless `T` is one of `Types...`. The function shall be `= delete` if there are multiple occurrences of `T` in `Types...`.

Refs https://github.com/mapbox/geometry.hpp/issues/27

**Comment by tomilov** [comment]
`decltype(1234) == int` and `int` is convertible to `bool` freely.

**Comment by jfirebaugh** [comment]
@tomilov Correct.

I think the necessary change here is as simple as:

```diff
diff --git a/variant.hpp b/variant.hpp
index db5d3c8..1fb57df 100644
--- a/variant.hpp
+++ b/variant.hpp
@@ -585,7 +585,7 @@ class variant
 
     // http://isocpp.org/blog/2012/11/universal-references-in-c11-scott-meyers
     template <typename T, typename Traits = detail::value_traits<T, Types...>,
-              typename Enable = typename std::enable_if<Traits::is_valid>::type>
+              typename Enable = typename std::enable_if<Traits::is_direct>::type>
     VARIANT_INLINE variant(T&& val) noexcept(std::is_nothrow_constructible<typename Traits::target_type, T&&>::value)
         : type_index(Traits::index)
     {
```

**Comment by jfirebaugh** [comment]
`boost::variant` allows conversion, but protects against ambiguity where `mapbox::util::variant` does not:

This compiles and prints 0 (1 was likely expected):

```
    mapbox::util::variant<bool, uint64_t> mbv(1234);
    std::cout << mbv.which();
```

This does not compile:

```
    boost::variant<bool, uint64_t> bv(1234);
    std::cout << bv.which();
```

```
/Users/john/Development/variant/mason_packages/headers/boost/1.60.0/include/boost/variant/variant.hpp:1558:28: error: call to member function 'initialize' is ambiguous
              initializer::initialize(
              ~~~~~~~~~~~~~^~~~~~~~~~
/Users/john/Development/variant/mason_packages/headers/boost/1.60.0/include/boost/variant/variant.hpp:1735:9: note: in instantiation of function template specialization
      'boost::variant<bool, unsigned long long>::convert_construct<int>' requested here
        convert_construct( detail::variant::move(operand), 1L);
        ^
test/bench_variant.cpp:186:36: note: in instantiation of function template specialization 'boost::variant<bool, unsigned long long>::variant<int>' requested here
    boost::variant<bool, uint64_t> bv(1234);
                                   ^
```

Furthermore, [the most recent standard proposal](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0088r1.html) uses a similar bounded conversion rule based on overload resolution over a set of imaginary functions `FUN(T_i)`.

I'm 👍  on implementing this approach too.

**Comment by kkaefer** [comment]
A simple example where this bit me:

```cpp
#include <mapbox/variant.hpp>
​
#include <string>
​
using value = mapbox::util::variant<std::nullptr_t, std::string>;
​
struct value_visitor {
    bool operator()(const std::string& v) const {
        return !v.empty();
    }
};
​
int main() {
    mapbox::util::apply_visitor(value_visitor{}, value{std::nullptr_t()});
}
```

The visitor doesn't have an explicit `operator()` for `std::nullptr_t`, so it gets autoconverted to a `std::string`, which segfaults at runtime.

**Comment by jfirebaugh** [comment]
@kkaefer I don't think that example would be fixed by disallowing ambiguous `variant` constructors or assignments, since there's no construction or assignment happening during visits. It's the implicit `std::nullptr_t` ⇢ `std::string` conversion that's the issue, and AFAIK there's no way to disable that specifically in the visitor context.

I wish there were, because implicit conversion in the visitor context is definitely dangerous. Another case where it comes up is defining a visitor for `mapbox::geometry::geometry`. If the visitor has `operator()(const geometry&)` (e.g. for recursive visits to `geometry_collection` elements), then that overload will be used for any other geometry variant type you forgot, since they all implicitly convert back to `geometry`.

**Comment by artemp** [comment]
> boost::variant allows conversion, but protects against ambiguity where mapbox::util::variant does not

It looks a bit more complicated then that. Consider

```c++
boost::variant<bool, std::string> v("test");
```

`v` is holding bool ^ 

Requiring exact type matching and out-source all conversions to the client looks like the easiest approach but it'll break current code for sure.  I'm experimenting with only allowing conversions if there is only **one**  possible conversion to avoid ambiguity but I'm not 100% sure this is the best solution just yet, either .. Tricky to get this one right :) 


/cc @jfirebaugh @springmeyer

**Comment by artemp** [comment]
The change below doesn't quite work in a intuitive way 

```diff
diff --git a/include/mapbox/variant.hpp b/include/mapbox/variant.hpp
index d7c1e86..5c67600 100644
--- a/include/mapbox/variant.hpp
+++ b/include/mapbox/variant.hpp
@@ -120,13 +120,30 @@ struct convertible_type<T>
     static constexpr std::size_t index = invalid_value;
 };
 
+
+template <typename T, typename... Types>
+struct count_convertibles;
+
+template <typename T, typename First, typename... Types>
+struct count_convertibles<T, First, Types...>
+{
+    static constexpr std::size_t value = 1 + count_convertibles<T,Types...>::value;
+};
+
+template <typename T>
+struct count_convertibles<T>
+{
+    static constexpr std::size_t value = 0;
+};
+
 template <typename T, typename... Types>
 struct value_traits
 {
     using value_type = typename std::remove_const<typename std::remove_reference<T>::type>::type;
     static constexpr std::size_t direct_index = direct_type<value_type, Types...>::index;
     static constexpr bool is_direct = direct_index != invalid_value;
-    static constexpr std::size_t index = is_direct ? direct_index : convertible_type<value_type, Types...>::index;
+    static constexpr std::size_t index = is_direct ? direct_index : count_convertibles<value_type, Types...>::value == 1
+        ? convertible_type<value_type, Types...>::index : invalid_value;
     static constexpr bool is_valid = index != invalid_value;
     static constexpr std::size_t tindex = is_valid ? sizeof...(Types)-index : 0;
     using target_type = typename std::tuple_element<tindex, std::tuple<void, Types...>>::type;
```

**Comment by springmeyer** [comment]
Closing, this landed in https://github.com/mapbox/variant/commit/71ac8fdf96e547dca34fe58c5cd8d1dce2ef0dac. It is debatable how this should interact with semver versioning. It can create new compile errors, but only in cases where variant was misused and would have been buggy at runtime. So those compile errors should be fixed. Currently have assigned this to the next release: v1.1.3. Will reconsider if this need to be promoted to v1.2.x or v2.x after further testing.
