### ISSUE TITLE
Using GCC/G++ on Darwin 

### ISSUE THREAD

**Issue by artemp** [mapbox/variant#108]
Currently it's not possible to build targets on OS X using GCC due to extra flags: https://github.com/mapbox/variant/blob/master/Makefile#L14-L18

```bash
CXX=/usr/local/gcc-5.2.0/bin/g++-5.2.0 make test bench sizes
mkdir -p ./out
/usr/local/gcc-5.2.0/bin/g++-5.2.0 -c -o out/unit.o test/unit.cpp -Itest/include -O0 -g -DDEBUG -fno-inline-functions -Wall -pedantic -Wextra -Wsign-compare -Wsign-conversion -Wshadow -Wunused-parameter -std=c++11  -stdlib=libc++
g++-5.2.0: error: unrecognized command line option ‘-stdlib=libc++’
make: *** [out/unit.o] Error 1
```

The solution is to remove those flags - correctly setup toolchain will select correct run-time automatically.

**Comment by artemp** [comment]
@springmeyer 55579f0 fixes compilations with gcc on Darwin and all tests are passing https://travis-ci.org/mapbox/variant/builds/129431785

**Comment by springmeyer** [comment]
👍

**Comment by springmeyer** [comment]
I wonder if homebrew provides binaries of g++-5 we could use? Installing g++ from source on OSX travis machines would be a non-starter, but if we could pull binaries from homebrew then testing this might be feasible.
