### ISSUE TITLE
Next release planning

### ISSUE THREAD

**Issue by springmeyer** [mapbox/variant#123]
Next release is currently planned to be v1.1.3. Aiming to release next week.
- remaining open issues: https://github.com/mapbox/variant/milestone/4
- closed issues: https://github.com/mapbox/variant/milestone/4?closed=1

Plan is to:
- Release once #122 is closed (@artemp)
- Re-assess if this should instead be called v1.2.x or v.2.x per https://github.com/mapbox/variant/issues/100#issuecomment-255449150 (@springmeyer)
- Signoff: @jfirebaugh @kkaefer @daniel-j-h

**Comment by jfirebaugh** [comment]
> if this should instead be called v1.2.x or v.2.x 

No strong opinion, either is fine with me.

> Signoff

👍

**Comment by daniel-j-h** [comment]
Sounds good :+1: - you can test the pre-release in osrm-backend, should be as easy as switching out the mapbox/variant directory and letting all tests /benchmarks on Travis run. From what I can see skimming the issues I expect no real differences.

**Comment by springmeyer** [comment]
👍 I confirmed osrm-backend builds fine @daniel-j-h

**Comment by daniel-j-h** [comment]
Ping - I just updated our libosmium dependency and remembered variant wanting to do a release, too ;) anything blocking? Anything new in the meantime?

**Comment by springmeyer** [comment]
Available at https://github.com/mapbox/variant/releases/tag/v1.1.3
