### ISSUE TITLE
Remove dependency on std::ostream

### ISSUE THREAD

**Issue by springmeyer** [mapbox/variant#14]
I think we should remove the [printer](https://github.com/mapbox/variant/blob/cf7f7bef518d7dd67d74e84bdbaf40a6c5826114/variant.hpp#L327-L344) and [`operator<<`](https://github.com/mapbox/variant/blob/cf7f7bef518d7dd67d74e84bdbaf40a6c5826114/variant.hpp#L520-L528), because this forces custom types to also offer an `operator<<` which is not ideal. Not all users of the library may want to have to depend on `#include <ostream>`.

**Comment by joto** [comment]
`operator<<` has been moved to `variant_io.hpp` a while ago in 24dcab23.
