### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by springmeyer** [mapbox/variant#159]
We need to start keeping a changelog. Example: I noticed `v1.1.5` has been tagged. But what is in it? What changed?

/cc @artemp - can you get this started?

**Comment by artemp** [comment]
Added [CHANGELOG](https://github.com/mapbox/variant/blob/master/CHANGELOG.md) in 555436f715e5e0929a13664f0911ecc4931356d1

**Comment by joto** [comment]
I have been using [this change log format](http://keepachangelog.com/en/1.0.0/) for a while now and can recommend it.

**Comment by artemp** [comment]
@joto looks good for future entries, thanks!

**Comment by springmeyer** [comment]
> I have been using this change log format for a while now and can recommend it.

👍  I'm supportive of http://keepachangelog.com/en/1.0.0/. The [bad practices](http://keepachangelog.com/en/1.0.0/#bad-practices) hits on key points: we should not use commit message logs (too much noise, too little signal). Rather we should clearly summarize major changes. @artemp - let's plan to adhere to this going forward.
