### ISSUE TITLE
How can I  make the recursive variant  serializable?

### ISSUE THREAD

**Issue by iomeone** [mapbox/variant#169]
Thank you for the library, I just want some advice which is the best way to serialize it to the string 
and restore the variant from the string , thank you very much!

**Comment by artemp** [comment]
@iomeone - `the best` way is subjective here and depends on your actual types. I'd start by looking how boost::variant implements serialisation for recursive types.  If you're OK with a plain text  then JSON or YAML might be a good solution. HTH

**Comment by iomeone** [comment]
I see, and I will recursively tranverse the datatype, and translate it to plain text, thanks anyway!
