### ISSUE TITLE
cant use bool and string in a variant

### ISSUE THREAD

**Issue by mahdy-asady** [mapbox/variant#179]
i cant use below code:
variant<int, double, string, bool> a = "Test";

but when i remove bool variable type it works fine!

**Comment by lightmare** [comment]
```c++
variant<int, double, string, bool> a = "Test";
```
is ambiguous, because the compiler has two equally good conversions available:
a) `const char*` to `bool` (implicit pointer-to-bool conversion)
b) `const char*` to `std::string` (using std::string conversion constructor)

You need to disambiguate it yourself, e.g.:
```c++
variant<int, double, string, bool> a = string("Test");
```
