### ISSUE TITLE
Q: copy elision always happening at operator=(variant<Types...> other)?

### ISSUE THREAD

**Issue by DennisOSRM** [mapbox/variant#29]
https://github.com/mapbox/variant/blob/master/variant.hpp#L557 defines the assignment operator that should be elided by the compiler. Does that also happen if any member type of the variant doesn't have a move c'tor?

**Comment by springmeyer** [comment]
This is stale, and its unclear if it might still be relevant because the link points to lines of code in master that have shifted.
