### ISSUE TITLE
(potentially) big parameter passed by value

### ISSUE THREAD

**Issue by DennisOSRM** [mapbox/variant#36]
Looks like the assignment operator does something costly [here](https://github.com/mapbox/variant/blob/master/variant.hpp#L560-L564):

```C++
560    VARIANT_INLINE variant<Types...>& operator=(variant<Types...> other)
561    {
562        swap(*this, other);
563        return *this;
564    }
```

Would it make sense to pass the _other_ variant by reference?

**Comment by artemp** [comment]
@DennisOSRM - this  'combined' `operator=(..)` invokes copy constructor for copyable and move constructor for movable types. At least this is an intent. Copy can be expensive, indeed, but need it for exception safety guarantee.  Can you share you object implementation to see what we can do ?

Canonical implementation for copyable objects would look something like

```c++
VARIANT_INLINE variant<Types...>& operator=(variant<Types...> const& other)
 {
         if ( this == &other) return *this;
        variant<Types...> tmp(other);  // <-------  this is potentially costly but required for exception safety
        swap(*this, tmp);
        return *this;
 }
```
Note, `expensive` copy ctor ^

**Comment by artemp** [comment]
@DennisOSRM - having a second look - I think we should introduce separate copy and move operator=
implementations

**Comment by springmeyer** [comment]
@artemp - anything more to do here or can we close this up?

**Comment by lightmare** [comment]
Not relevant anymore as there are now explicit overloads for `V const&` and `V &&` in master.

**Comment by artemp** [comment]
Yep, closing
