### ISSUE TITLE
compile-time assertion for is<T> with invalid T

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/variant#43]
Is it possible to make a usage of `is<T>()`, where `T` is a type not in `typename... Types`, to fail a compile-time assertion? I just hit this case at runtime after changing `Types` and forgetting to update a few uses of `if (val.is<T>())` that are now invalid (guaranteed to return false).

**Comment by artemp** [comment]
@jfirebaugh - Should be possible, I'll take a look

**Comment by artemp** [comment]
```bash
./variant.hpp:646:9: error: static_assert failed "invalid type in T in `is<T>()` for this variant"
```

Could you check this works for you and I'll close this ticket ?

**Comment by artemp** [comment]
fixed in 91ba0301a672ea0a3131390d44d304c5493de84a

**Comment by artemp** [comment]
```c++

mapbox::util::variant<int,double> var;
if (var.is<std::string>())  // <== compile time error ./variant.hpp:646:9: error: static_assert failed "invalid type in T in `is<T>()` for this variant"
{
    ....
}
```

@jfirebaugh - closing for now, let me know if any issues

**Comment by springmeyer** [comment]
re-opening - needs some kind of unit test (which will be tricky).

**Comment by artemp** [comment]
@springmeyer - this is compile time error so unit test won't cut unless we resort to some `make` hacks. ^^

**Comment by artemp** [comment]
@joto - Does https://github.com/mapbox/variant/commit/0c7e4e2c6908d988e216a6a953bf2342ebcac415 address this issue and can it be closed ?

**Comment by springmeyer** [comment]
Certainly does, let's chat next steps over at #77
