### ISSUE TITLE
Hard coding of version number

### ISSUE THREAD

**Issue by joto** [mapbox/variant#47]
Why is the version number hard coded? See https://github.com/mapbox/variant/blob/master/variant.hpp#L34 and https://github.com/mapbox/variant/blob/master/test/unit.cpp#L34-L42.

/cc @artemp @springmeyer

**Comment by springmeyer** [comment]
I added this. Not sure what is wrong with hardcoding - this is being done similar to https://github.com/mapnik/mapnik/blob/master/include/mapnik/version.hpp#L26-L30 (which is done like boost/version.hpp). Do you have ideas for alternative ways?

**Comment by joto** [comment]
@springmeyer With hard coding I meant that the comment indicates that it always has to have version 0.1.0 (because only that will result in 100) and the test checks that it has that version. I guess at some point we want to change the version number than the comment will be wrong and the test will fail.

**Comment by springmeyer** [comment]
Ah, I see now. Yeah, my assumption is that the comment and test would be updated each time the version is bumped. But I'm open to removing them to avoid drift.
