### ISSUE TITLE
Recursive wrapper doesn't default initialize POD types. On purpose?

### ISSUE THREAD

**Issue by joto** [mapbox/variant#51]
Recursive wrapper of a POD type (`recursive_wrapper<int>` or so) doesn't default initialize its value. It calls `new T`, not `new T{}`. Is this on purpose?

@artemp? @springmeyer?

**Comment by artemp** [comment]
@joto - recursive wrapper implementation is borrowed from boost and yes it uses `new T` for performance to avoid default initialising POD members I think. Do you see this might break anything and we need to change it?

**Comment by joto** [comment]
I guess this is okay as long as it is properly documented. It is just one of those things that can trip you up, it is not obvious what is supposed to happen here. I'll document the current behaviour.

**Comment by joto** [comment]
Documented in 6eb8fea08a22b9040011c20f998e1e77bc78e188.
