### ISSUE TITLE
Defining functions in class or not?

### ISSUE THREAD

**Issue by joto** [mapbox/variant#52]
Currently all through the code some class member functions are only declared in the classes and later defined and some are defined directly in the classes. Because this is all header-only this distinction isn't really necessary, but the inconsistency can be confusing. I suggest moving all definitions into the classes, but either way is fine with me. As long as it is consistent.

Opinions?

**Comment by artemp** [comment]
@joto - I have no strong opinion regarding this, being consistent sounds like a good approach.

**Comment by joto** [comment]
Fixed in 6eb8fea08a22b9040011c20f998e1e77bc78e188.
