### ISSUE TITLE
Provide .clang-format for consistent code style

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/variant#55]
It would be great to have a `.clang-format` file for this repository (in all C++ repositories in my opinion).

**Comment by springmeyer** [comment]
:+1: thanks for the suggestion. Once work has settled in master I will grab the `.clang-format` from `osrm-backend` and apply it here before releasing (refs #78)

**Comment by daniel-j-h** [comment]
Great! Feel free to customize it to your own needs (e.g. the osrm 80 col. limit seems limiting in my opinion). It's more important to have a style to rely on than what exactly it looks like.

**Comment by artemp** [comment]
@daniel-j-h @springmeyer - tried to come up with reasonable `.clang-format` that would work across projects. it almost works and integrates OK with emacs but there are couple features that I'm not happy about. 
For example 

```c++
add
("one",1)
("two",2)
;
``` 
I'd like it to be as above but `clang-format` insists on changing it to

```c++
add("one",1)("two",2); 
```
@daniel-j-h - do you have some ideas how to fix this ?

**Comment by artemp** [comment]
### Integration 

#### Emacs 
```lisp
;; clang-format integration
;; set path to `clang-format`
(setq exec-path (append exec-path '("/opt/llvm/bin")))
(load "/opt/llvm/share/clang/clang-format.el")
(global-set-key [C-M-tab] 'clang-format-region)
(add-hook 'c++-mode-hook
	  '(lambda ()
	     (add-hook 'before-save-hook #'clang-format-buffer nil t)))
```
this is what I had to put into `.emacs`

**Comment by artemp** [comment]
`.clang-format` - this is what I came up with so far
https://gist.github.com/artemp/d59d92d7db407d7a7640  -

**Comment by artemp** [comment]
Ok, one `hack-ish` way that works is
```c++
BOOST_FUSION_ADAPT_STRUCT(mapnik::unary_function_call,       //
                          (mapnik::unary_function_impl, fun) //
                          (mapnik::unary_function_call::argument_type, arg))
```  -- _Note empty comments `//`

**Comment by artemp** [comment]
Done in 5436e10b77544306a2eeaf214525de6562260ca2, closing

**Comment by daniel-j-h** [comment]
Yes, the comment solution is what I'm also usually doing. Integration via `vim-clang` is also great for vim/neovim!
