### ISSUE TITLE
Prefer `inline` over `static inline` for free standing function definitions in header file

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/variant#56]
While looking through the osrm-backend source code my curiously grep-ing revealed that we had `staic inline` free standing function definitions in header files https://github.com/Project-OSRM/osrm-backend/pull/1872. Because we include variant in a subdirectory, I also found a few issues in this project.

The problem is this: when you mark free standing functions as `static inline` instead of just `inline` they can not get merged across TUs and therefore produce code bloat which is bad for the binaries size, the CPU's instruction cache, and so on.

Please also see the discussion at:

- https://groups.google.com/forum/#!topic/mozilla.dev.platform/Ulw9HoZbSyQ
- http://stackoverflow.com/a/12836392

The second problem is that variant conditionally toggles between inline and no inline [via this macro](https://github.com/mapbox/variant/blob/3ac6e46d01f3a8fbf9944e19d806bc3d456d1a0c/variant.hpp#L14-L27). For free standing functions we always need `inline` in order to not violate the One-Definition-Rule. This has nothing to do with efficiency, but instead correctness. Looking at the free standing functions, as long as they are non-fully specialized templates, they are inline by default.

**Comment by joto** [comment]
Looking at the code I find 6 free functions, all at the end: Four versions of `apply_visitor()` and two versions of `get()`. If I understand you correctly, all these functions would be declared `inline`, but not `static`. All other functions declared `static` are in classes, so they must stay the way they are.

**Comment by lightmare** [comment]
> would be declared inline, but not static.

They should not be static, but also don't need to be declared inline:

> as long as they are non-fully specialized templates, they are inline by default.



> The second problem is that variant conditionally toggles between inline and no inline via this macro.

It only depends on _MSC_VER and NDEBUG, which I don't think can vary between TUs linked together.

**Comment by joto** [comment]
@lightmare So, just remove the `static` in the four `apply_visitor()` declarations?

**Comment by daniel-j-h** [comment]
Yes, as long as they are not fully specialized. Or be explicit and mark them inline nevertheless.

**Comment by lightmare** [comment]
Note that if `!_MSC_VER && NDEBUG` the VARIANT_INLINE macro expands to `inline __attribute...`
