### ISSUE TITLE
optional should provide == and != operators

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/variant#64]

**Comment by joto** [comment]
Our `optional` implementation is very incomplete compared to the [upcoming standard](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3848.html), `boost::optional` or [this implementation](https://github.com/akrzemi1/Optional). Do we want to keep working on our own?

/cc @springmeyer 

See also #63.

**Comment by jfirebaugh** [comment]
I [switched mapbox-gl-native over to experimental/optional](https://github.com/mapbox/mapbox-gl-native/pull/3616) earlier this week. I support deprecating or removing our implementation.

**Comment by springmeyer** [comment]
> I support deprecating or removing our implementation.

Same :+1: . For the next tagged release let's remove it.

**Comment by kirbyfan64** [comment]
:(

**Comment by springmeyer** [comment]
> I switched mapbox-gl-native over to experimental/optional earlier this week. I support deprecating or removing our implementation.

@jfirebaugh I saw you mention that you hit problems with `experimental::optional`? Do you see value in keeping `mapbox::optional` around longer or no?

**Comment by jfirebaugh** [comment]
mapbox-gl-native no longer uses `mapbox::optional`. We work around a couple of `experimental::optional` bugs on various implementations:

* `bool operator!=() const` is sometimes missing (use `!(a == b)` instead)
* `T* operator->() const` is sometimes broken (use `operator*` instead)

**Comment by springmeyer** [comment]
Thanks @jfirebaugh - re-closing this issue then: We'll stick with the current deprecation and future removal (at v2.x)
