### ISSUE TITLE
Add travis job that tests -std=c++14

### ISSUE THREAD

**Issue by springmeyer** [mapbox/variant#66]
`std=c++11` is hardcoded at the end of https://github.com/mapbox/variant/blob/master/Makefile#L5

We should instead make that overridable with an option so that we can start testing compiles/unit tests in `c++14` mode as well as `c++11` on travis.

**Comment by joto** [comment]
I have added two tests running clang 3.8 and g++ 4.9 in c++14 mode to the travis config. Of course we could do this on all compilers, but it would double the amount of tests to be run for not that much gain.
@springmeyer re-open or change .travis config yourself, if you think we need to check more variations.
