### ISSUE TITLE
Remove optional

### ISSUE THREAD

**Issue by joto** [mapbox/variant#68]
Remove implementation and tests of `optional` as per #64.

**Comment by artemp** [comment]
@joto - I'm not aware of any current usage of optional,  fine to remove on my end.

**Comment by springmeyer** [comment]
We've deprecated for now (https://github.com/mapbox/variant/issues/64#issuecomment-182592572). Not seeing a need to keep this open: we can remove at 2.0 but 2.0 is not actionable yet.
