### ISSUE TITLE
Mutable visitor

### ISSUE THREAD

**Issue by joto** [mapbox/variant#71]
It seems visitors are currently copied around and so when they have some data inside any changes are not visible after the `apply_visitor()` call. This is different from how boost does it. I have more or less copied [a test](https://github.com/mapbox/variant/blob/0d8fb2ee8ae45f971b8956d49ba425043e169ea1/test/t/visitor.cpp#L47-L75) from boost for this.

**Comment by artemp** [comment]
Initial implementation : https://github.com/mapbox/variant/tree/visitor-no-copy
It will require quite a few changes/corrections in mapnik, mostly const/non-const correctness in visitor functors.

/cc @joto @springmeyer @flippmoke

**Comment by lightmare** [comment]
In `dispatcher<F, V, R, T, Types...>::apply` (https://github.com/mapbox/variant/commit/fedf7d6a3eede22b9af0ce695deded8c9b45eb45#diff-dab208458c807c54b530c13b19c80187R294), `F` is not deduced type, `F &&` is rvalue reference, not forwarding.

**Comment by lightmare** [comment]
Forwarding must happen in `apply_visitor` as you did in that commit, and also in `variant::visit` (where F is deduced):
```c++
    template <typename F, typename V>
    auto VARIANT_INLINE
    static visit(V & v, F && f)
        -> decltype(detail::dispatcher<F&& , V,
                    typename detail::result_of_unary_visit<F&& ,
                    first_type>::type, Types...>::apply(v, std::forward<F>(f)))
    {
        using R = typename detail::result_of_unary_visit<F&& , first_type>::type;
        return detail::dispatcher<F&&, V, R, Types...>::apply(v, std::forward<F>(f));
    }
```

Also consider simplifying `visit` by finding `R` just once (not sure MSVC will like that, last time I tried SFINAE it wasn't happy ;)
```c++
    template <typename F, typename V,
              typename R = typename detail::result_of_unary_visit<F && , first_type>::type>
    auto VARIANT_INLINE
    static visit(V const& v, F && f)
        -> decltype(detail::dispatcher<F && , V, R, Types...>::apply_const(v, std::forward<F>(f)))
    {
        return detail::dispatcher<F && , V, R, Types...>::apply_const(v, std::forward<F>(f));
    }
```

**Comment by artemp** [comment]
@lightmare - all good points! I'm going to defer to @joto on ^ as he was working on similar solutions as of today :)

**Comment by joto** [comment]
@lightmare re your first comment: Just tested this, and yes, it works with `F` alone, but I think `F&&` makes the intention more clear here. Is there any drawback to using `F&&`?
re your second comment: I have also thought of pulling the R out. But maybe we could move the derivation of R into the dispatcher function and that might even be better. Not sure yet, have to try.

Anyway, I merged the `visitor-no-copy` branch now and we can try out these things separately.

**Comment by lightmare** [comment]
@joto you're right, it probably doesn't make a difference. But I don't see what intention it makes more clear, quite the contrary -- it confused me into thinking that `F` is not a reference type already.

**Comment by joto** [comment]
@lightmare if I see the pattern of a function parameter declared as `T&& t` and the parameter is then only used in `forward<T>(t)` I stop thinking and just know that this parameter will be forwarded perfectly and I am done. I don't need to know how the function is called or how the function looks, that this call forwards to.

**Comment by springmeyer** [comment]
As visitor-no-copy is merged, let's close this now and create new tickets for any followups.
