### ISSUE TITLE
v1.1.0 release

### ISSUE THREAD

**Issue by springmeyer** [mapbox/variant#78]
@artemp @joto @lightmare - once your work in current master has settled let's cut a new release. I propose aiming for next Tuesday the 2nd for release.

 I'm proposing it is tagged as v1.1.0 (our only other currently tagged release is v1.0.0).

Let's use this ticket to track overall discussion on:

  - When we are ready to release
  - Upgrades needed for major downstream consumers (mapbox-gl-native, geojson-vt, osrm, mapnik)

/cc @daniel-j-h @flippmoke @kkaefer @jfirebaugh

**Comment by springmeyer** [comment]
This happened: https://github.com/mapbox/variant/releases/tag/v1.1.0

**Comment by daniel-j-h** [comment]
Thanks for this release, we're using it in osrm-backend already without problems so far!

**Comment by jfirebaugh** [comment]
Likewise in mapbox-gl-native. 👍
