### ISSUE TITLE
Tested compiler versions

### ISSUE THREAD

**Issue by joto** [mapbox/variant#79]
The list of tested compiler versions and the actually tested versions in travis/appveyor are not in sync. Appveyor seems only to test MSVC 2014. Clang 3.4 is not tested any more.

And there are some suspicious mentionings of version `3.4` packages in the `.travis.yml` file that look like copy-and-paste errors. Or are some of the packes only available in older versions?

**Comment by springmeyer** [comment]
Added missing compilers above ^^. However clang++3.4 won't work because catch.hpp is broken: https://github.com/philsquared/Catch/issues/535. So, I'll pull clang++3.4 from travis now and the readme.
