### ISSUE TITLE
Inconsistent handling in get<>() for reference_wrapper

### ISSUE THREAD

**Issue by joto** [mapbox/variant#82]
When storing `std::reference_wrapper<T const>` in variant `v`, the handling of `v.get<...>()` and `get<...>(v)` is inconsistent. One allows the use of the non-const version. The other doesn't. See this test: https://github.com/mapbox/variant/blob/a43ef1eed7f9dc4eb52fda4edb73ffec5e284650/test/t/variant.cpp#L451-L454

**Comment by artemp** [comment]
Fixed and test is re-enabled, closing
