### ISSUE TITLE
warning: comparing floating point is unsafe

### ISSUE THREAD

**Issue by springmeyer** [mapbox/variant#97]
```
deps/mapbox/variant/variant.hpp:506:20: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
        return lhs == rhs;
               ~~~ ^  ~~~
```

/cc @artemp

**Comment by artemp** [comment]
@springmeyer - yes, and yes we know what's going on, aren't we :) .

We can provide specialisations for floating point numbers using suitable EPS defined in <cfloat> ( `float`,`double`, `long double`)

```c++
struct equal_comp
{
    template <typename T>
    bool operator()(T const& lhs, T const& rhs) const
    {
        return lhs == rhs;
    }
};
```

But I'm not 100% sure this is worth pursuing 
/cc @springmeyer @joto

**Comment by joto** [comment]
The implementation for `==` is okay. It is outside the scope of `variant` to "fix" equality comparison on floating point types. If you are putting floating point values into a variant, you should know not not use `==` on it.

But we should not use this in our tests. I had removed floating points from our tests for this reason:
https://github.com/mapbox/variant/commit/48b565c1afd5d2481890878b3386417c52220199

@springmeyer What did you compile to get this error? Did a floating point comparison creep back into our test code?

**Comment by springmeyer** [comment]
Okay, thanks. So this is a misusage. Moving to -> https://github.com/mapnik/mapnik/issues/3357
