### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/variant#98]
The README doesn't describe how to use the library. It should have basic examples of defining a variant type, defining and using a visitor, and so on..

**Comment by daniel-j-h** [comment]
Yes please. That's the reason we're [pointing to the Boost.Variant docs](https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/json_container.hpp#L47-L63) for our users.

There are differences between Boost.Variant and mapbox/variant that are not documented (e.g. member function vs free standing `get`, no `is<T>` in Boost.Variant, and so on). It would be great to document not only the usage but also the differences to popular alternatives such as Boost.Variant.

**Comment by artemp** [comment]
@jfirebaugh @daniel-j-h - good call
